source ~/.zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme
source ~/.p10k.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
